
import __ASTRO_IMAGE_IMPORT_ZyXb9p from "./sao-theme-01.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-meizu%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZSQR5v from "./images/baidu.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2mlNfx from "./images/samsung.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zg3lAX from "./images/pc.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1jxphO from "./images/pc2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z23Cm5o from "./images/mobile.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1STnXP from "./3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZXk5Oy from "./4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1k89wx from "./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2JMFh from "./5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ROut0 from "./6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1NoMCh from "./7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2ld32n from "./8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md";
export default new Map([["./sao-theme-01.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-meizu%2Findex.md", __ASTRO_IMAGE_IMPORT_ZyXb9p], ["./images/baidu.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md", __ASTRO_IMAGE_IMPORT_ZSQR5v], ["./images/samsung.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2mlNfx], ["./images/pc.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md", __ASTRO_IMAGE_IMPORT_Zg3lAX], ["./images/pc2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md", __ASTRO_IMAGE_IMPORT_1jxphO], ["./images/mobile.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fp7i%2Findex.md", __ASTRO_IMAGE_IMPORT_Z23Cm5o], ["./3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1STnXP], ["./4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md", __ASTRO_IMAGE_IMPORT_ZXk5Oy], ["./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md", __ASTRO_IMAGE_IMPORT_1k89wx], ["./5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2JMFh], ["./6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md", __ASTRO_IMAGE_IMPORT_ROut0], ["./7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md", __ASTRO_IMAGE_IMPORT_1NoMCh], ["./8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsao-theme%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2ld32n]]);
		